"""進捗（advancement）の木。ハンドブックの「進み具合」の章もこれを使う。

ADVANCEMENTS は (id, 親, アイコン, 枠, 条件, 段階, 日本語の題, 日本語の説明, 英語の題, 英語の説明)。
条件:
  ('tick',)                 入ったらすぐ（根）
  ('item', 'xxx')           singulo:xxx を手に入れる（minecraft: で始まればバニラ）
  ('milestone', 'id')       Singulo の出来事（formed/<マルチブロック>, discover/<遺構>, ignite, wormhole_open, records_all など）
  ('kill', 'entity_id')     倒す
枠: task / goal / challenge
"""

ADVANCEMENTS = [
    ('root', None, 'handbook', 'task', ('tick',), 1,
     'Singulo', '質量からエネルギーを取り出す。まずはハンドブックを開こう',
     'Singulo', 'Extract energy from mass. Open the handbook to begin'),
    # ---------------- 段階1
    ('steel', 'root', 'steel_ingot', 'task', ('item', 'steel_ingot'), 1,
     '鋼の時代', '鋼鉄インゴットを作る', 'Age of Steel', 'Make a steel ingot'),
    ('ceramic', 'steel', 'white_ceramic_composite', 'task', ('item', 'white_ceramic_composite'), 1,
     '白い外装', 'ホワイトセラミック複合材を焼く', 'White Casing', 'Fire white ceramic'),
    ('circuit', 'ceramic', 'basic_circuit', 'task', ('item', 'basic_circuit'), 1,
     '最初の回路', '基礎回路を作る', 'First Circuit', 'Make a basic circuit'),
    ('thermo', 'circuit', 'thermoelectric_generator', 'goal', ('item', 'thermoelectric_generator'), 1,
     '温度差', '熱電発電機を作る。高温と低温のブロックで挟むと発電する', 'Temperature Gradient',
     'Build a thermoelectric generator and put it between hot and cold'),
    ('compressor', 'thermo', 'compressor', 'task', ('item', 'compressor'), 1,
     'すべては質量', '圧縮機を作る。質量モードで何でも固められる', 'Everything Is Mass', 'Build a compressor'),
    ('projector', 'circuit', 'holo_projector', 'task', ('item', 'holo_projector'), 1,
     '設計図は光で', 'ホロ投影機を作る。コントローラに使うと形が見える', 'Blueprints of Light',
     'Make a holo projector and use it on a controller'),
    ('archive', 'compressor', 'archive_terminal', 'task', ('item', 'archive_terminal'), 1,
     '旧文明の端末', 'アーカイブ端末を作る', 'Ancient Terminal', 'Build an archive terminal'),
    ('ruin_observation', 'archive', 'observation_log', 'goal', ('milestone', 'discover/observation_post'), 1,
     '旧文明の痕跡', '地表観測拠点の保管庫を開ける', 'Traces of the Ancients', 'Open an observation post cache'),
    # ---------------- 段階2
    ('tower', 'ruin_observation', 'cooling_tower_controller', 'goal', ('milestone', 'formed/cooling_tower'), 2,
     '絶対零度へ', '極低温冷却塔を組み上げる', 'Toward Absolute Zero', 'Form a cryogenic cooling tower'),
    ('coil', 'tower', 'superconducting_coil', 'goal', ('item', 'superconducting_coil'), 2,
     '抵抗ゼロ', '超伝導コイルを作る', 'Zero Resistance', 'Make a superconducting coil'),
    ('assembler', 'coil', 'precision_assembler', 'task', ('item', 'precision_assembler'), 2,
     '精密な手', '精密組立台を作る', 'Precise Hands', 'Build a precision assembler'),
    ('accelerator', 'coil', 'accelerator_controller', 'goal', ('milestone', 'formed/particle_accelerator'), 2,
     '衝突', '粒子加速器を組み上げる', 'Collision Course', 'Form a particle accelerator'),
    ('muon', 'accelerator', 'muon_catalyst', 'task', ('item', 'muon_catalyst'), 2,
     '最初の触媒', 'ミュオン触媒を作る', 'First Catalyst', 'Make a muon catalyst'),
    ('monopole', 'accelerator', 'magnetic_monopole', 'challenge', ('item', 'magnetic_monopole'), 2,
     '北だけの磁石', '磁気単極子を手に入れる', 'North Only', 'Obtain a magnetic monopole'),
    ('anchor', 'muon', 'worldline_anchor_small', 'task', ('item', 'worldline_anchor_small'), 2,
     '世界線の錨', 'ワールドライン・アンカー（小）を作る', 'Worldline Anchor', 'Build a small worldline anchor'),
    # ---------------- 段階3
    ('quantum', 'assembler', 'quantum_computing_module', 'goal', ('item', 'quantum_computing_module'), 3,
     '量子の時代', '量子演算モジュールを作る', 'Quantum Age', 'Make a quantum computing module'),
    ('entangled', 'quantum', 'entangled_element', 'task', ('item', 'entangled_element'), 3,
     '不気味な遠隔作用', '量子もつれ素子を作る', 'Spooky Action', 'Make entangled elements'),
    ('ruin_research', 'quantum', 'quantum_data_fragment', 'task', ('milestone', 'discover/research_building'), 3,
     '研究棟', '研究棟の保管庫を開ける', 'Research Building', 'Open a research building cache'),
    ('bose', 'entangled', 'bose_condensate_catalyst', 'task', ('item', 'bose_condensate_catalyst'), 3,
     '凝縮の合唱', 'BE凝縮触媒を作る', 'Condensate Choir', 'Make a BE condensate catalyst'),
    ('gauntlet', 'quantum', 'inertial_control_gauntlet', 'task', ('item', 'inertial_control_gauntlet'), 3,
     '慣性を手に', '慣性制御ガントレットを作る', 'Inertia in Hand', 'Make an inertial control gauntlet'),
    ('detector', 'quantum', 'gravitational_wave_detector', 'task', ('item', 'gravitational_wave_detector'), 3,
     '時空のさざ波', '重力波検出器を作る', 'Ripples in Spacetime', 'Build a gravitational wave detector'),
    # ---------------- 段階4
    ('compactor', 'bose', 'degenerate_compactor_controller', 'goal', ('milestone', 'formed/degenerate_compactor'), 4,
     '縮退圧', '縮退圧縮炉を組み上げる', 'Degeneracy Pressure', 'Form a degenerate compactor'),
    ('ruin_culture', 'bose', 'culture_data', 'task', ('milestone', 'discover/culture_facility'), 4,
     '封鎖区画', '封鎖培養施設の保管庫を開ける', 'Sealed Section', 'Open a culture facility cache'),
    ('crystal', 'ruin_culture', 'time_crystal_catalyst', 'goal', ('item', 'time_crystal_catalyst'), 4,
     '時間の結晶', '時間結晶触媒を育てる', 'Crystal of Time', 'Grow a time crystal catalyst'),
    ('cavity', 'compactor', 'casimir_cavity_controller', 'task', ('milestone', 'formed/casimir_cavity'), 4,
     '何もない空間の力', 'C空洞を組み上げる', 'The Force of Nothing', 'Form a C-Cavity'),
    ('exotic', 'cavity', 'exotic_matter', 'goal', ('item', 'exotic_matter'), 4,
     '負のエネルギー', 'エキゾチック物質を作る', 'Negative Energy', 'Make exotic matter'),
    ('furnace', 'compactor', 'degenerate_furnace_controller', 'task', ('milestone', 'formed/degenerate_furnace'), 4,
     '中性子星の炉', '縮退熱炉を組み上げる', 'Neutron Star Furnace', 'Form a degenerate furnace'),
    ('probe', 'crystal', 'probe_station', 'task', ('item', 'probe_station'), 4,
     '無人探査', '自動探査機ステーションを作る', 'Unmanned Expedition', 'Build a probe station'),
    # ---------------- 段階5
    ('ruin_final', 'exotic', 'anomaly_sample', 'goal', ('milestone', 'discover/final_lab'), 5,
     '重力異常点', '最終実験施設にたどり着く', 'Gravitational Anomaly', 'Reach the final lab'),
    ('warden', 'ruin_final', 'seal_console', 'challenge', ('kill', 'singulo:horizon_warden'), 5,
     '地平線の番人', 'ホライズン・ウォーデンを倒す', 'Horizon Keeper', 'Defeat the Horizon Warden'),
    ('seed', 'warden', 'singularity_seed', 'task', ('item', 'singularity_seed'), 5,
     '特異点の種', '特異点の種を目覚めさせる', 'Seed of a Singularity', 'Awaken a singularity seed'),
    ('reactor', 'seed', 'core_controller', 'goal', ('milestone', 'formed/penrose_reactor'), 5,
     'ジャイロスコープ', 'Pリアクターを組み上げる', 'Gyroscope', 'Form a P-Reactor'),
    ('ignite', 'reactor', 'core_controller', 'challenge', ('milestone', 'ignite'), 5,
     '事象の地平線', 'リアクターを点火し、ブラックホールを生む', 'Event Horizon', 'Ignite the reactor'),
    ('core', 'ignite', 'singularity_core', 'goal', ('item', 'singularity_core'), 5,
     'シンギュラリティ', 'シンギュラリティ・コアを作る', 'Singularity', 'Make a singularity core'),
    ('shield', 'core', 'shield_tower_core', 'task', ('milestone', 'formed/event_horizon_shield'), 5,
     '地平線の盾', 'イベントホライズン・シールド発生塔を組み上げる', 'Horizon Shield', 'Form a shield tower'),
    ('tipler', 'core', 'tipler_core', 'task', ('milestone', 'formed/tipler_cylinder'), 5,
     '時間を回す', 'Tシリンダーを組み上げる', 'Spinning Time', 'Form a T-Cylinder'),
    ('wormhole', 'core', 'wormhole_port', 'challenge', ('milestone', 'wormhole_open'), 5,
     '橋', 'ワームホールの口をつなぐ', 'Bridge', 'Connect a pair of wormhole mouths'),
    ('dark', 'ignite', 'halo_collector', 'task', ('milestone', 'dark_matter'), 5,
     '見えない質量', 'ダークマターを集める', 'Invisible Mass', 'Collect dark matter'),
    ('metric', 'core', 'metric_drive', 'task', ('item', 'metric_drive'), 5,
     '計量を曲げる', 'メトリック・ドライブを作る', 'Bending the Metric', 'Make a metric drive'),
    ('manipulator', 'core', 'graviton_manipulator', 'task', ('item', 'graviton_manipulator'), 5,
     '重力子', 'グラビトン・マニピュレーターを作る', 'Graviton', 'Make a graviton manipulator'),
    ('records', 'archive', 'record_fragment', 'challenge', ('milestone', 'records_all'), 5,
     '滅びの記録', '旧文明の記録をすべて解読する', 'Record of the Fall', 'Decode every ancient record'),
]
