"""アイテム・ブロックの説明文（ツールチップとハンドブックに出す）。

DESC[日本語名] = (日本語, English)。1〜2文で「何か・何に使うか」を書く。作り方と使い道の一覧は
gen_data.py がレシピから自動で足すので、ここには書かない。
"""

DESC = {
    # ---------------------------------------------------------------- 段階1 起動
    '鋼の素': ('鉄と石炭を混ぜた鋼鉄の原料。溶鉱炉で焼くと鋼鉄インゴットになる。',
             'A mix of iron and coal. Smelt it in a blast furnace to get steel.'),
    '鋼鉄インゴット': ('Singulo の装置の骨組みになる基本の金属。他modの鋼鉄も使える。',
                  'The basic structural metal. Steel from other mods works too.'),
    '未焼成セラミック': ('粘土・砂・ネザー水晶・骨粉を練ったもの。かまどで焼くとホワイトセラミック複合材になる。',
                  'Clay, sand, Nether quartz and bone meal, ready to be fired into white ceramic.'),
    'ホワイトセラミック複合材': ('白い外装と回路基板の材料。Singulo の装置の白い見た目はここから来る。',
                     'The white ceramic used for casings and circuit boards.'),
    '基礎回路': ('段階1の装置の頭脳になる回路。', 'The brain of every early machine.'),
    'Singuloハンドブック': ('右クリックで開く手引き書。目標や装置の使い方、マルチブロックの組み方が読める。',
                      'Right-click to open. Explains goals, machines, multiblocks and shows your progress.'),
    'ホロ投影機': ('コントローラに使うと正しい形を投影し、足りないブロックを教える。スニークして使うと大きさを切り替える。',
              'Use on a multiblock controller to project its shape and list missing blocks. Sneak-use to change size.'),
    '探索コンパス': ('いちばん近い遺構の方を指す。スニーク＋右クリックで探す遺構を変える。',
              'Right-click to point at the nearest ruin of the chosen kind. Sneak-use to change the kind.'),
    'クリエイティブ電源': ('クリエイティブ専用。電力が尽きない電源。隣の装置やケーブルへ受け取れるだけ送る。',
                 'Creative only. Endless power pushed into every neighbour.'),
    '無限の触媒': ('クリエイティブ専用の減らない触媒。右クリックでティアを変える。',
              'Creative only. A catalyst that never wears out. Right-click to change its tier.'),
    '組み立ての杖': ('クリエイティブ専用。コントローラに使うと一瞬で組み立てる。スニークで大きさを変える。',
               'Creative only. Instantly builds the multiblock of a controller. Sneak to change size.'),
    '熱電対モジュール': ('温度差から電気を起こす素子。熱電発電機の心臓部。',
                  'Turns a temperature difference into electricity.'),
    '基礎フレーム': ('ほとんどの装置の土台になる骨組み。', 'The frame almost every machine is built on.'),
    '鋼板': ('圧縮機で鋼鉄をのばした板。外装や部品に広く使う。', 'Pressed steel used for casings and parts.'),
    'セラミック基板': ('焼成炉で焼いた回路用の基板。', 'A fired ceramic board for circuits.'),
    '水素': ('電解槽で水から取り出すガス。ミュオン触媒の原料。', 'Gas split from water. Used to make muon catalysts.'),
    '酸素': ('電解槽の副産物。焼成炉に送ると炉温が上がる。', 'By-product of electrolysis. Boosts the kiln.'),
    '銅導線': ('段階1の電線。つないだ装置どうしで電力を分け合う。距離が長いと少し損失がある。',
             'Tier 1 power cable. Loses a little energy over distance.'),
    '白紙データカード': ('アーカイブ端末で記録を書き写す空のカード。', 'An empty card for copying records in the Archive Terminal.'),
    'データカード（観測ログ）': ('観測ログを書き写したカード。レシピで使える。', 'A copy of an observation log, usable in recipes.'),
    '圧縮ブロックLv1': ('質量モードの圧縮機で9単位の質量を固めたブロック。上位の圧縮ブロックと燃料の元。',
                    'Nine units of mass pressed together. The start of the compression chain.'),
    '質量ペレット': ('質量を固めた燃料。Pリアクターに投入して発電する。', 'Packed mass fuel for the P-Reactor.'),
    '熱電発電機': ('熱いブロックと冷たいブロックに挟むと発電する。最初の電源。'
              '最初の電源。', 'Place it between something hot and something cold to generate power. Your first generator.'),
    '焼成炉': ('セラミックや基板を高温で焼く装置。酸素を送ると速くなる。', 'Fires ceramics and boards. Oxygen makes it hotter.'),
    '圧縮機': ('板を作る。質量モードでは何でも吸い込み、圧縮ブロックや質量ペレットに固める。'
            '画面のボタンでモードを切り替える。', 'Presses plates. In mass mode it turns any item into mass for compressed blocks and pellets.'),
    '電解槽': ('水を水素と酸素に分ける。', 'Splits water into hydrogen and oxygen.'),
    'アーカイブ端末': ('記録をデータカードに写し、劣化した部品を直す。記録片の解読もできる。',
                 'Copies ruin records onto data cards, restores degraded parts and decodes record fragments.'),
    # ---------------------------------------------------------------- 段階2 極低温
    '冷却塔基部': ('極低温冷却塔の底の 5×5 の土台。', 'The 5×5 foundation of the tower.'),
    '冷却塔冷却帯': ('冷却塔のくびれに3段ごとに巻く、冷媒の流れる帯。', 'Coolant bands around the waist, every third layer.'),
    '冷却塔頂部リム': ('冷却塔のてっぺんの 5×5 の縁。', 'The 5×5 rim at the top of the tower.'),
    '冷却塔通気格子': ('冷却塔のてっぺんの内側 3×3 をふさぐ格子。冷えた蒸気が抜ける。', 'Grate closing the top; the vapour escapes through it.'),
    '縮退圧縮炉フレーム': ('縮退圧縮炉の箱の12本の辺になる枠。', 'Frame along the 12 edges of the press.'),
    '縮退圧縮炉装甲板': ('縮退圧縮炉の外装。どの装甲板もマルチブロック搬入出ポートに替えられる。', 'Plating; any plate can be swapped for an I/O port.'),
    '縮退圧縮炉ラム': ('縮退圧縮炉の天面の中心。中のアンビルへ打ち下ろす。', 'Top centre; hammers down onto the anvil.'),
    '縮退圧縮炉アンビル': ('縮退圧縮炉の底面の中心の受け台。', 'Bottom centre; takes the blows.'),
    '縮退圧縮炉冷却口': ('縮退圧縮炉の側面の最上段に並ぶ冷却口。', 'Cooling vents along the top row of each side.'),
    '縮退圧縮炉観察窓': ('縮退圧縮炉の側面の中段の中央。打ち下ろす瞬間が見える。', 'Middle of each side; watch the ram strike.'),
    'C空洞フレーム': ('C空洞の辺になる枠。', 'Frame along the cavity edges (not the corners).'),
    'C空洞真空ポンプ': ('C空洞の箱の8つの角に置く真空ポンプ。', 'Vacuum pumps on the eight corners.'),
    'C空洞容器壁': ('C空洞の外装。どの容器壁もマルチブロック搬入出ポートに替えられる。', 'Vessel wall; any can be swapped for an I/O port.'),
    'C空洞磁気シールド': ('C空洞の側面の中段、観察窓の両わきに置く磁気シールド。', 'Magnetic shields either side of each window.'),
    'C空洞観察窓': ('C空洞の側面の中段の中央。鏡の間のゆらぎが見える。', 'Middle of each side; shows the vacuum between the mirrors.'),
    'シールド発生塔基壇': ('シールド発生塔の土台。2段目の辺は搬入出ポートに替えられる。', 'The 5×5 two-layer plinth; its upper edge takes I/O ports.'),
    'シールド発生塔電力コイル': ('シールド発生塔の基壇の2段目の内側 3×3。', 'Inner 3×3 of the upper plinth layer.'),
    'シールド発生塔本体': ('シールド発生塔の 3×3 の胴の四隅と、尖塔の根元。', 'Corners of the 3×3 body and the base of the spire.'),
    'シールド発生塔導波管': ('シールド発生塔の胴の各面の中央と尖塔の中ほど。中を昇るエネルギーが見える。', 'Middle of each body face; shows the rising energy.'),
    'シールド発生塔放射冠': ('シールド発生塔のてっぺん。ここからドームを放つ。', 'The top of the tower; the dome is cast from here.'),
    'Tシリンダーフレーム': ('Tシリンダーの格納筒の12本の辺になる枠。', 'Frame along the 12 edges of the housing.'),
    'Tシリンダー外殻': ('Tシリンダーの外装。どの外殻もマルチブロック搬入出ポートに替えられる。', 'Housing; any panel can be swapped for an I/O port.'),
    'Tシリンダー軸受': ('Tシリンダーの上下の面の中心。円柱の軸を受ける。', 'Top and bottom centre; carries the cylinder axle.'),
    'Tシリンダー観察窓': ('Tシリンダーの側面の中央の縦5段。回る円柱が見える。', 'Five-high slit in each side; shows the spinning cylinder.'),
    'Tシリンダー時間結晶ホルダー': ('Tシリンダーの側面の中段、窓の両わき。', 'Either side of each window, middle layer.'),
    'ワームホール生成器外殻': ('ワームホール生成器の球の外殻。どの外殻もマルチブロック搬入出ポートに替えられる。', 'Sphere shell; any can be swapped for an I/O port.'),
    'ワームホール生成器場コイル': ('ワームホール生成器の赤道の段、窓の両わき。', 'Equator, either side of each window.'),
    'ワームホール生成器収束器': ('ワームホール生成器の球の上下の中心。', 'Top and bottom centre of the sphere.'),
    'ワームホール生成器観察窓': ('ワームホール生成器の赤道の段の各面の中央。育つ渦が見える。', 'Middle of each face at the equator; shows the vortex.'),
    '冷却塔外壁': ('極低温冷却塔の外壁。輪の辺は搬入出ポートに替えられる。',
             'Cooling Tower wall. Panels on the 5×5 rings can be swapped for I/O ports.'),
    '冷却塔ガラス': ('極低温冷却塔のくびれの観察窓。中の熱交換コアが青く光るのが見える。',
              'Window in the tower waist; the cores glow blue inside.'),
    '熱交換コア': ('冷却塔の中心に積む熱交換器。',
             'Heat exchangers stacked up the middle of the tower.'),
    'マルチブロック搬入出ポート': ('マルチブロックの外装板と入れ替える搬入出口。つないだ物はコントローラへ届き、できた物と電力は隣へ自動で出る。'
                        'つないだケーブルやパイプはコントローラへ届き、できたものや発電した電力は隣へ自動で押し出す。',
                        'Replaces a plain shell panel of a multiblock (not frames or functional parts; for the accelerator, either side of the controller). '
                        'Cables and pipes reach the controller, and outputs and generated power are pushed out automatically.'),
    '冷却塔コントローラ': ('極低温冷却塔の頭脳。高いほど速い。',
                 'Goes in the middle of the front, second layer. The tower is 7–15 high; taller is faster.'),
    '極低温冷却塔': ('空気から液体窒素を、高さ10以上ならヘリウムから液体ヘリウムを作るマルチブロック。',
                  'Liquefies nitrogen (and helium at height 10+).'),
    '冷却塔拡張（高さ10）': ('冷却塔を高さ10以上にすると液体ヘリウムを作れる。', 'Build the tower 10+ high to liquefy helium.'),
    '液体窒素': ('77 K の冷却材。超伝導の材料作りに使う。', 'A 77 K coolant for superconductors.'),
    '超伝導コイル': ('電気抵抗ゼロのコイル。段階2以降の装置の要。', 'A zero-resistance coil, core of tier 2 tech.'),
    '超伝導線材': ('超伝導コイルとケーブルの材料。', 'Wire for coils and cables.'),
    '超伝導ケーブル': ('損失なしで大電力を運ぶ段階2のケーブル。', 'Tier 2 lossless high-capacity cable.'),
    '加速管': ('粒子加速器のリングを作る管。', 'Tube segment of the Particle Accelerator ring.'),
    '収束磁石': ('粒子加速器のリングの四隅と、リングの1/4以上に置く磁石。', 'Magnet for the ring corners and at least 1/4 of the ring.'),
    '加速器コントローラ': ('粒子加速器の頭脳。正方形のリングに接して置く。大きいほど速い。',
                   'Controls a square ring 8–32 wide. Bigger rings are faster and yield more monopoles.'),
    '粒子加速器': ('粒子をぶつけてミュオン束や磁気単極子を作るマルチブロック。', 'Collides particles into muon bundles and rare monopoles.'),
    'ミュオン束': ('ミュオンの束。ミュオン触媒の原料。', 'A bundle of muons, the base of muon catalysts.'),
    '触媒反応器': ('触媒を作る装置。ミュオン触媒はここで作る。', 'Makes catalysts, starting with the muon catalyst.'),
    'ミュオン触媒': ('ティア2の触媒。使い切ると失活触媒が残る。',
                 'Tier 2 catalyst with a lifetime. Leaves a spent catalyst when used up.'),
    '極低温タービン': ('液体窒素や液体ヘリウムの気化で発電する。', 'Generates power from evaporating cryogens.'),
    '宇宙線ミュオン収集器': ('空が見える高い場所で、電力なしでミュオンを集める。',
                     'Collects cosmic-ray muons for free high up under open sky.'),
    'SMESセル': ('超伝導の磁気エネルギー貯蔵。大量の電力をためる。右クリックで画面を開く。', 'Superconducting energy storage.'),
    '精密組立台': ('段階2以降のほとんどの部品と装置を組み立てる作業台。', 'Assembles most parts and machines from tier 2 on.'),
    'ワールドライン・アンカー（小）': ('触媒を入れると、周りのチャンクを読み込み続ける。',
                          'Keeps nearby chunks loaded while fed a catalyst.'),
    '単極子アップグレード': ('装置の単極子スロットに挿すと処理速度×2、電力効率+50%。1台に1個まで。',
                    'Insert into a machine\'s monopole slot: ×2 speed and 50% better power efficiency.'),
    '記録片': ('旧文明の記録の断片。アーカイブ端末で解読できる。',
            'A fragment of an ancient record. Decode it in the Archive Terminal to add it to the handbook.'),
    '解読した記録': ('右クリックで読むと、ハンドブックに記録が加わる。',
              'Right-click to read it and add the next ancient record to your handbook.'),
    'ストレンジ物質': ('ストレンジレットに変えられた超高密度の物質。良い燃料になる。',
                'Ultra-dense matter left by strangelets. Worth 100 mass and usable for degenerate shells.'),
    'ストレンジレット': ('周りのブロックを少しずつストレンジ物質に変える。磁気瓶で回収する。',
                 'Converts nearby blocks into strange matter. Contain it with a Magnetic Bottle.'),
    '磁気単極子': ('粒子加速器の衝突でごくまれに生まれる粒子。', 'A theoretical particle born in about 1 of 1000 collisions.'),
    # ---------------------------------------------------------------- 段階3 量子
    'ヘリウム': ('深層岩などを砕くと出る。冷却塔で液体ヘリウムにする。', 'Extracted from deep rock. Liquefy it in the tall tower.'),
    '液体ヘリウム': ('4 K の冷却材。量子部品とボース凝縮に要る。', 'A 4 K coolant for quantum parts.'),
    'データカード（量子データ片）': ('量子データ片を書き写したカード。', 'A copy of a quantum data fragment.'),
    '量子演算モジュール': ('段階3以降の上位装置の頭脳。', 'The brain of advanced machines.'),
    '量子もつれ合成器': ('2個1組の量子もつれ素子を作る。', 'Produces entangled elements in pairs.'),
    '量子もつれ素子': ('必ず2個1組で生まれる素子。検出器や遠隔連携の材料。', 'Always made in pairs. Used in detectors and links.'),
    'レーザー冷却器': ('原子をレーザーで冷やし、冷却原子・光格子基板・BE凝縮触媒を作る。', 'Laser-cools atoms into cold atoms, lattices and condensates.'),
    '冷却原子': ('絶対零度近くまで冷えた原子。', 'Atoms cooled close to absolute zero.'),
    '光格子基板': ('光で原子を並べた基板。量子部品の土台。', 'Atoms held in a lattice of light.'),
    'BE凝縮触媒': ('ティア3の触媒。ミュオン触媒より強く長持ち。', 'Tier 3 catalyst.'),
    '量子熱機関': ('触媒の量子効果で発電する。触媒のティアが高いほど出力が大きい。', 'A catalyst-driven generator.'),
    '重力波検出器': ('最終実験施設のおおよその方角と距離を教える。', 'Points toward the nearest gravitational anomaly.'),
    'ニュートリノ・スキャナー': ('使うと周りの遺構の部品と鉱石の輪郭を、地形越しに10秒間浮かび上がらせる。電力を使う。',
                      'Reveals ruins and ores through terrain for 10 seconds.'),
    '慣性スタビライザー': ('半径16の中で、爆発がブロックを壊さなくなる。', 'Stops explosions from breaking blocks within 16 blocks.'),
    '残響共鳴器': ('残響の欠片を型にして複製する。', 'Copies echo shards using a template shard.'),
    '慣性制御ガントレット': ('右クリック長押しで、目の前の1体を浮かせたり引き寄せたりする。',
                     'Hold right-click to levitate or pull one small mob. Sneak-use to switch modes.'),
    # ---------------------------------------------------------------- 段階4 時間
    '圧縮ブロックLv2': ('圧縮ブロックLv1 を固めたもの。縮退熱炉の燃料。', 'Nine Lv1 blocks (eight if mixed). Fuel for the Degenerate Furnace.'),
    '圧縮ブロックLv3': ('さらに高密度に固めたブロック。', 'An even denser block.'),
    '圧縮ブロックLv2（混成）': ('3種類以上の元ブロックから作った Lv1 なら、8個で Lv2 になる。', 'Lv1 made from 3+ kinds of blocks needs only 8 for Lv2.'),
    '縮退圧縮炉コントローラ': ('縮退圧縮炉の頭脳。5×5×5 の手前の面の下から2段目の中央に置く。', 'Middle of the front, second layer, of the 5×5×5 press.'),
    '縮退圧縮炉': ('物質を縮退するまで押しつぶすマルチブロック。縮退物質殻や炉殻を作る。', 'Crushes matter into degenerate shells and reactor parts.'),
    '金属圧縮ブロックLv1': ('金属だけを固めた圧縮ブロック。', 'A compressed block made only of metals.'),
    '金属圧縮ブロックLv2': ('金属圧縮ブロックをさらに固めたもの。人工星核の材料。', 'Denser metal block, used for artificial star cores.'),
    '縮退物質殻': ('中性子星の物質でできた殻。特異点の種を包む。', 'A shell of neutron-star matter.'),
    '鏡面プレート': ('C空洞の天面と底面の内側 3×3 に置き、向かい合う2枚の鏡にする。', 'Inner 3×3 of the cavity top and bottom: two facing mirrors.'),
    'C空洞コントローラ': ('C空洞の頭脳。5×5×5 の手前の面の下から2段目の中央に置く。', 'Middle of the front, second layer, of the 5×5×5 cavity.'),
    'C空洞': ('向かい合う鏡の間の真空から、エキゾチック物質とアクシオン凝縮体を作る。',
                  'Creates negative energy between mirrors to make exotic matter.'),
    'アクシオン凝縮体': ('真空中のアクシオンを集めた凝縮体。', 'Condensed axions gathered from the vacuum.'),
    'データカード（培養データ）': ('培養データを書き写したカード。', 'A copy of culture data.'),
    '時間結晶育成槽': ('時間結晶触媒を育てる。電力が足りないと純度が下がる。',
                 'Grows time crystal catalysts. Underpowering lowers their purity.'),
    '時間結晶触媒': ('ティア4の触媒。上位装置の多くがこれで動く。', 'Tier 4 catalyst used by most advanced devices.'),
    'エキゾチック物質': ('負のエネルギー密度を持つ物質。重力系の装置とワームホールの燃料。', 'Matter with negative energy density. Fuels gravity tech.'),
    '縮退熱炉フレーム': ('縮退熱炉の辺になる重い枠。', 'The heavy frame along the 12 edges of the 5×5×7 furnace.'),
    '縮退熱炉外装板': ('縮退熱炉の外装。どの外装板もマルチブロック搬入出ポートに替えられる。', 'Furnace plating. Any panel can be swapped for a Multiblock I/O Port.'),
    '縮退熱炉ピストン部': ('縮退熱炉の上下の面の中心に置き、燃料を上下から押しつぶす。', 'Sits in the middle of the top and bottom faces and crushes the fuel.'),
    '縮退熱炉放熱フィン': ('縮退熱炉の側面の、観察窓の両わきに置く放熱板。', 'Radiators on either side of each furnace window.'),
    '縮退熱炉熱交換管': ('縮退熱炉の中の四隅に立てる、熱を運ぶ銅の管。', 'Copper pipes standing in the four inner corners of the furnace.'),
    '縮退熱炉観察窓': ('縮退熱炉の側面の中央の縦3段。押しつぶされて白熱する炉心が見える。', 'The middle column of each furnace side; shows the glowing core.'),
    '縮退熱炉コントローラ': ('縮退熱炉の頭脳。どれか1つの側面の、下から2段目の中央に置く。', 'Goes in the middle of a side, second layer from the bottom.'),
    '縮退熱炉': ('圧縮ブロックLv2 を押しつぶして 20 MFE/t を出す発電機。', 'A large generator burning Lv2 blocks.'),
    'トポロジカル導線': ('段階4の大容量ケーブル。', 'Tier 4 high-capacity cable.'),
    'トロイダル磁気コイル': ('ドーナツ形の強い磁場を作るコイル。', 'Makes a strong toroidal field.'),
    'SMESモジュール': ('大容量の蓄電ブロック。', 'High-capacity energy storage.'),
    '自動探査機ステーション': ('発見済みの下位の遺構へ探査機を飛ばし、回収物を自動で持ち帰る。', 'Sends probes to discovered ruins to fetch loot.'),
    '磁気瓶': ('磁場でストレンジレットを捕まえる瓶。漏れ出したストレンジ物質に使うと封じ込めて回収できる。',
            'Captures strangelets and contains leaking strange matter.'),
    # ---------------------------------------------------------------- 段階5 特異点
    'ホライズン・バス': ('最大容量のケーブル。リアクターの点火に要る。', 'The tier 5 cable, needed to ignite the reactor.'),
    '炉殻ブロック': ('Pリアクターの3本の円環を作る外殻。', 'Shell of the reactor\'s three rings.'),
    'ジャイロ駆動部': ('リアクターの3本の円環が交わる6点に置く。', 'Placed where the reactor rings cross.'),
    '抽出ポート': ('リアクターの搬入出口。リングの炉殻と入れ替えて、好きな数だけ置ける。', 'Power/fuel port for the reactor. Replaces any ring shell block (not the gyro drives).'),
    '重力場安定化ユニット': ('炉心制御装置の材料。', 'A component of the core controller.'),
    '炉心制御装置': ('Pリアクターの頭脳。炉心の真下に置き、画面から点火する。',
                 'Placed 5 below the core centre. Ignite the reactor from its screen.'),
    'Pリアクター': ('ブラックホールの回転から電力を取り出す最終の発電所。', 'Draws energy from a spinning black hole.'),
    'Hコレクター': ('触媒モードのリアクターでH凝縮体を集める。', 'Collects H-Condensate in catalyst mode.'),
    'ジェット・コレクター': ('リアクターのジェットからジェット凝縮体を集める。', 'Collects jet condensate from the reactor.'),
    'エルゴスフィア・リング': ('高スピンの炉心からエキゾチック物質を取り出す。', 'Extracts exotic matter from a fast-spinning core.'),
    'ジェット凝縮体': ('相対論的ジェットの粒子。人工星核の材料。', 'Particles from the relativistic jet.'),
    '人工星核': ('ネザースターの代わりになる星の核。', 'A star core that replaces nether stars.'),
    'H凝縮体': ('ホーキング放射を集めた凝縮体。シンギュラリティ・コアの材料。', 'Condensed Hawking radiation.'),
    '特異点封入台': ('特異点の種やシンギュラリティ・コアを作る。', 'Encapsulates singularities.'),
    '特異点の種': ('リアクターに入れて点火すると炉心になる。', 'Becomes a black hole core when ignited.'),
    'シンギュラリティ・コア': ('最上位の触媒。シールドの完全版などに使う。', 'The tier 5 catalyst.'),
    'ハロー捕集器': ('稼働中の炉心の近くで、ダークマターを集める。', 'Gathers dark matter near a running core.'),
    'ダークマター': ('重力以外ほとんど反応しない物質。普通の入れ物からは漏れる。炉心に直接入れると質量になる。',
               'Interacts only through gravity. Leaks from ordinary containers.'),
    '重力閉じ込めタンク': ('ダークマターを保管できる唯一のタンク。壊すと中身ごと運べる。電力が切れると漏れる。',
                   'The only tank that holds dark matter. Keeps its contents when broken.'),
    '炉心安定化コイル': ('Pリアクターのリングの斜め45°に置く、地平線を安定させるコイル。', 'Coils at the 45° points of the reactor rings.'),
    '炉心質量警報器': ('リングの炉殻と入れ替えて置く。炉心の質量が上限に達すると赤石信号を出し、崩壊が近いほど強くなる。',
                'Replaces a shell on a reactor ring. Emits redstone when the core reaches its mass limit, stronger near collapse.'),
    '空のBH格納容器': ('小さなブラックホールを閉じ込めるための容器。', 'A vessel for holding a tiny black hole.'),
    '小型BH格納容器': ('小さなブラックホールを閉じ込めた容器。持つと周りの景色が歪む。', 'Holds a tiny black hole. Bends light around it.'),
    'ブラックホール爆弾': ('投げると、当たった所に小さなブラックホールが開き、周りを飲み込む。', 'Thrown: opens a tiny black hole that swallows its surroundings.'),
    '設定カード': ('装置の設定を写して、ほかの装置に貼る。', 'Copies a machine\'s settings to another.'),
    'ニュートリノ観測所': ('電力で広い範囲を調べ続け、鉱石と遺構を近くの人に見せ続ける。右クリックで表示を切り替える。',
                   'Keeps scanning a wide area and shows ores and ruins to nearby players. Use to toggle.'),
    'シールド許可証': ('シールド発生塔に入れると、登録した人だけが守りの中で作業できる。'
                '右クリックで自分を、ほかのプレイヤーに右クリックでその人と自分を登録する。放射冠だけはだれでも壊せる。',
                'Put it in a shield tower: only registered players may build, break or take items inside. Use to register yourself; '
                'use on a player to register them and you. Anyone can break the emitter crown.'),
    'シールド発生塔コア': ('イベントホライズン・シールド発生塔の頭脳。基壇の2段目の手前の中央に置く。', 'Front middle of the upper plinth layer.'),
    'イベントホライズン・シールド発生塔': ('半径32の中を爆発・荒らし・敵の湧きから守る塔。', 'Protects a 32-block radius from explosions, griefing and hostile spawns.'),
    'ワールドライン・アンカー（上位）': ('上位のアンカー。シンギュラリティ・コアを埋め込むと消費なしになる。',
                          'Advanced chunk loader. Embedding a Singularity Core makes it free and maximal.'),
    'メトリック・ドライブ': ('持っていると、低重力・無重力・高重力を切り替えられる。', 'Switch between low gravity, flight and high gravity.'),
    'グラビトン・マニピュレーター': ('重力を操る杖。持ち上げた物をためて投げ飛ばせる。',
                     'The full gravity tool. Hold left-click to use; while levitating, charge with right-click and release to throw.'),
    'Tコア': ('Tシリンダーの頭脳。5×5×9 の手前の面の下から2段目の中央に置く。', 'Middle of the front, second layer, of the 5×5×9 housing.'),
    'Tシリンダー': ('周りの時間を速め、半径16の装置や作物を2倍速にする。', 'Speeds up time within 8 blocks.'),
    'ワームホール生成器コア': ('ワームホール生成器の頭脳。球の底の 3×3 の手前の列の中央に置く。', 'Front middle of the bottom 3×3 of the sphere.'),
    'ワームホール生成器': ('100 MFE/t を10秒受けて、一対のワームホールの口を作る。', 'Creates a pair of wormhole mouths from 100 MFE/t for 10 s.'),
    '不安定なワームホールの口': ('60秒以内に固定化装置へ入れないと崩壊する。', 'Collapses unless stabilized within 60 s.'),
    'ワームホールの口': ('置くと対の口とつながる。エキゾチック物質で維持する。', 'Links to its twin. Needs exotic matter upkeep.'),
    'ワームホール固定化装置': ('不安定な口をエキゾチック物質で固定化し、置ける口にする。', 'Stabilizes wormhole mouths.'),
    'ワームホール・ポート': ('口から8ブロック以内に置くと、向こう側の装置と電力・アイテム・液体を直結する。', 'Links machines through a wormhole.'),
    # ---------------------------------------------------------------- 遺構の回収物
    '観測ログ': ('地表観測拠点で拾う記録。アーカイブ端末でデータカードに書き写して使う。', 'A record from observation posts. Copy it onto data cards.'),
    '劣化した制御ユニット': ('地表観測拠点で拾う部品。アーカイブ端末で修復すると使える。', 'A degraded part. Restore it in the Archive Terminal.'),
    '制御ユニット': ('修復した旧文明の制御ユニット。使用回数がある。', 'A restored ancient control unit with limited uses.'),
    '量子データ片': ('研究棟で拾う記録。', 'A record from research buildings.'),
    '劣化した冷却原子トラップ': ('研究棟で拾う部品。レーザー冷却器で復元する。', 'Restore it in the Laser Cooler.'),
    '冷却原子トラップ': ('復元した冷却原子トラップ。', 'A restored cold atom trap.'),
    '劣化した時間結晶の種': ('封鎖培養施設で拾う種。復元すると時間結晶を育てられる。', 'Restore it to grow time crystals.'),
    '時間結晶の種': ('時間結晶触媒の種。', 'Seed for time crystal catalysts.'),
    '培養データ': ('封鎖培養施設で拾う記録。', 'A record from the culture facility.'),
    '劣化したアノマリー・サンプル': ('最終実験施設で拾うサンプル。', 'A sample from the final lab.'),
    'アノマリー・サンプル': ('復元した重力異常のサンプル。', 'A restored anomaly sample.'),
    '休眠した特異点の種': ('ホライズン・ウォーデンが守る種。特異点封入台で目覚めさせる。', 'Guarded by the Horizon Warden. Awaken it in the encapsulator.'),
    '遺構パネル': ('旧文明の建材。', 'Ancient building panel.'),
    'ひび割れた遺構パネル': ('ひびの入った旧文明の建材。', 'Cracked ancient panel.'),
    '苔むした遺構パネル': ('苔に覆われた旧文明の建材。', 'Mossy ancient panel.'),
    '割れた遺構ガラス': ('旧文明の窓。', 'Ancient window glass.'),
    '遺構の照明': ('今も光る旧文明の照明。', 'An ancient lamp that still glows.'),
    '遺構保管庫': ('遺構の回収物が入った保管庫。空になってから数日で中身が戻る。', 'Holds ruin loot. Refills some days after emptied.'),
    '警備機ドック': ('警備ドローンを出撃させるドック。', 'Launches security drones.'),
    '封印コンソール': ('最終実験施設の封印。触れるとホライズン・ウォーデンが起動する。', 'Touch it to wake the Horizon Warden.'),
    '失活したミュオン触媒': ('使い切ったミュオン触媒。触媒反応器で一部を回収できる。', 'A used-up catalyst. Partly recyclable.'),
    '失活したBE凝縮触媒': ('使い切ったBE凝縮触媒。下のティアの触媒として約25%回収できる。', 'Recycle it into lower-tier catalysts.'),
    '失活した時間結晶触媒': ('使い切った時間結晶触媒。下のティアの触媒として約25%回収できる。', 'Recycle it into lower-tier catalysts.'),
    '失活したシンギュラリティ・コア': ('使い切ったシンギュラリティ・コア。下のティアの触媒として約25%回収できる。', 'Recycle it into lower-tier catalysts.'),
}
