"""アイテム・ブロックの説明文（ツールチップとハンドブックに出す）。

DESC[日本語名] = (日本語, English)。1〜2文で「何か・何に使うか」を書く。作り方と使い道の一覧は
gen_data.py がレシピから自動で足すので、ここには書かない。
"""

DESC = {
    # ---------------------------------------------------------------- 段階1 起動
    '鋼の素': ('鉄と石炭を混ぜた鋼鉄の原料。溶鉱炉で焼くと鋼鉄インゴットになる。',
             'A mix of iron and coal. Smelt it in a blast furnace to get steel.'),
    '鋼鉄インゴット': ('Singulo の装置の骨組みになる基本の金属。他modの鋼鉄も使える。',
                  'The basic structural metal. Steel from other mods works too.'),
    '未焼成セラミック': ('粘土と砂を練ったもの。かまどで焼くとホワイトセラミック複合材になる。',
                  'Clay and sand, ready to be fired into white ceramic.'),
    'ホワイトセラミック複合材': ('白い外装と回路基板の材料。Singulo の装置の白い見た目はここから来る。',
                     'The white ceramic used for casings and circuit boards.'),
    '基礎回路': ('段階1の装置の頭脳になる回路。', 'The brain of every early machine.'),
    'Singuloハンドブック': ('右クリックで開く手引き書。段階ごとの目標、装置の使い方、マルチブロックの組み方、進み具合が読める。',
                      'Right-click to open. Explains goals, machines, multiblocks and shows your progress.'),
    'ホロ投影機': ('マルチブロックのコントローラに使うと、正しい形を半透明で投影し、足りないブロックをチャットに出す。'
              'スニークして使うと大きさを切り替える。',
              'Use on a multiblock controller to project its shape and list missing blocks. Sneak-use to change size.'),
    '探索コンパス': ('右クリックで、選んだ種類のいちばん近い遺構を探して針がそちらを向く（距離も出る）。スニーク＋右クリックで探す遺構を切り替える。',
              'Right-click to point at the nearest ruin of the chosen kind. Sneak-use to change the kind.'),
    'クリエイティブ電源': ('クリエイティブ専用。電力が尽きない電源。隣の装置やケーブルへ受け取れるだけ送る。',
                 'Creative only. Endless power pushed into every neighbour.'),
    '無限の触媒': ('クリエイティブ専用。減らない触媒。右クリックでティア（2〜5）を切り替える。',
              'Creative only. A catalyst that never wears out. Right-click to change its tier.'),
    '組み立ての杖': ('クリエイティブ専用。マルチブロックのコントローラに使うと、その向きのまま一瞬で組み立てる。スニークで大きさを切り替える。',
               'Creative only. Instantly builds the multiblock of a controller. Sneak to change size.'),
    '熱電対モジュール': ('温度差から電気を起こす素子。熱電発電機の心臓部。',
                  'Turns a temperature difference into electricity.'),
    '基礎フレーム': ('ほとんどの装置の土台になる骨組み。', 'The frame almost every machine is built on.'),
    '鋼板': ('圧縮機で鋼鉄をのばした板。外装や部品に広く使う。', 'Pressed steel used for casings and parts.'),
    'セラミック基板': ('焼成炉で焼いた回路用の基板。', 'A fired ceramic board for circuits.'),
    '水素': ('電解槽で水から取り出すガス。ミュオン触媒の原料。', 'Gas split from water. Used to make muon catalysts.'),
    '酸素': ('電解槽の副産物。焼成炉に送ると炉温が上がる。', 'By-product of electrolysis. Boosts the kiln.'),
    '銅導線': ('段階1の電線。つないだ装置どうしで電力を分け合う。距離が長いと少し損失がある。',
             'Tier 1 power cable. Loses a little energy over distance.'),
    '白紙データカード': ('アーカイブ端末で記録を書き写す空のカード。', 'An empty card for copying records in the Archive Terminal.'),
    'データカード（観測ログ）': ('観測ログを書き写したカード。レシピで使える。', 'A copy of an observation log, usable in recipes.'),
    '圧縮ブロックLv1': ('質量モードの圧縮機で9単位の質量を固めたブロック。上位の圧縮ブロックと燃料の元。',
                    'Nine units of mass pressed together. The start of the compression chain.'),
    '質量ペレット': ('質量を固めた燃料。Pリアクターに投入して発電する。', 'Packed mass fuel for the P-Reactor.'),
    '熱電発電機': ('高温のブロック（溶岩・かまど・焚き火など）と低温のブロック（水・氷など）に挟むと発電する。'
              '最初の電源。', 'Place it between something hot and something cold to generate power. Your first generator.'),
    '焼成炉': ('セラミックや基板を高温で焼く装置。酸素を送ると速くなる。', 'Fires ceramics and boards. Oxygen makes it hotter.'),
    '圧縮機': ('板を作るほか、質量モードでは何でも「質量」として吸い込み、圧縮ブロックや質量ペレットに固める。'
            '画面のボタンでモードを切り替える。', 'Presses plates. In mass mode it turns any item into mass for compressed blocks and pellets.'),
    '電解槽': ('水を水素と酸素に分ける。', 'Splits water into hydrogen and oxygen.'),
    'アーカイブ端末': ('遺構で拾った記録をデータカードに書き写し、劣化した部品を修復・復元する。記録片の解読もここで行う。',
                 'Copies ruin records onto data cards, restores degraded parts and decodes record fragments.'),
    # ---------------------------------------------------------------- 段階2 極低温
    '冷却塔外壁': ('極低温冷却塔の外壁。', 'Wall block of the Cryogenic Cooling Tower.'),
    '冷却塔ガラス': ('極低温冷却塔の窓。外壁の代わりに使える。', 'Window block for the Cooling Tower.'),
    '熱交換コア': ('冷却塔の中心の列に積む熱交換器。「高さ−2」個以上要る。', 'Stack these in the tower core: at least height − 2.'),
    '冷却塔ポート': ('冷却塔の搬入出口。パイプやケーブルをつなぐ。', 'Input/output port of the Cooling Tower.'),
    '冷却塔コントローラ': ('極低温冷却塔の頭脳。3×3の筒（高さ5〜15）の外周に置く。高いほど速い。ホロ投影機で形を確認できる。',
                   'Controls a 3×3 tower, 5–15 high. Taller is faster. Check the shape with the Holo Projector.'),
    '極低温冷却塔': ('空気から液体窒素を、高さ10以上ならヘリウムから液体ヘリウムを作るマルチブロック。',
                  'Liquefies nitrogen (and helium at height 10+).'),
    '冷却塔拡張（高さ10）': ('冷却塔を高さ10以上にすると液体ヘリウムを作れる。', 'Build the tower 10+ high to liquefy helium.'),
    '液体窒素': ('77 K の冷却材。超伝導の材料作りに使う。', 'A 77 K coolant for superconductors.'),
    '超伝導コイル': ('電気抵抗ゼロのコイル。段階2以降の装置の要。', 'A zero-resistance coil, core of tier 2 tech.'),
    '超伝導線材': ('超伝導コイルとケーブルの材料。', 'Wire for coils and cables.'),
    '超伝導ケーブル': ('損失なしで大電力を運ぶ段階2のケーブル。', 'Tier 2 lossless high-capacity cable.'),
    '加速管': ('粒子加速器のリングを作る管。', 'Tube segment of the Particle Accelerator ring.'),
    '収束磁石': ('粒子加速器のリングの四隅と、リングの1/4以上に置く磁石。', 'Magnet for the ring corners and at least 1/4 of the ring.'),
    '加速器コントローラ': ('粒子加速器の頭脳。正方形のリング（一辺8〜32）に接して置く。大きいほど速く、単極子も出やすい。',
                   'Controls a square ring 8–32 wide. Bigger rings are faster and yield more monopoles.'),
    '粒子加速器': ('粒子をぶつけてミュオン束や磁気単極子を作るマルチブロック。', 'Collides particles into muon bundles and rare monopoles.'),
    'ミュオン束': ('ミュオンの束。ミュオン触媒の原料。', 'A bundle of muons, the base of muon catalysts.'),
    '触媒反応器': ('触媒を作る装置。ミュオン触媒はここで作る。', 'Makes catalysts, starting with the muon catalyst.'),
    'ミュオン触媒': ('ティア2の触媒（寿命あり）。触媒装置に入れると動き、使い切ると失活触媒が残る。',
                 'Tier 2 catalyst with a lifetime. Leaves a spent catalyst when used up.'),
    '極低温タービン': ('液体窒素や液体ヘリウムの気化で発電する。', 'Generates power from evaporating cryogens.'),
    '宇宙線ミュオン収集器': ('空が見える高い場所（Y=100以上、Y=200で最大）で宇宙線のミュオンを電力なしで集める。',
                     'Collects cosmic-ray muons for free high up under open sky.'),
    'SMESセル': ('超伝導の磁気エネルギー貯蔵。大量の電力をためる。右クリックで画面を開く。', 'Superconducting energy storage.'),
    '精密組立台': ('段階2以降のほとんどの部品と装置を組み立てる作業台。', 'Assembles most parts and machines from tier 2 on.'),
    'ワールドライン・アンカー（小）': ('触媒を入れると周りのチャンクを常に読み込む（ミュオン触媒で半径1、BE凝縮触媒で2）。',
                          'Keeps nearby chunks loaded while fed a catalyst.'),
    '単極子アップグレード': ('装置の単極子スロットに挿すと処理速度×2、電力効率+50%。1台に1個まで。',
                    'Insert into a machine\'s monopole slot: ×2 speed and 50% better power efficiency.'),
    '記録片': ('遺構の保管庫からときどき出る旧文明の記録の断片。アーカイブ端末で解読すると、ハンドブックの「旧文明の記録」に追加される。',
            'A fragment of an ancient record. Decode it in the Archive Terminal to add it to the handbook.'),
    '解読した記録': ('記録片を解読したもの。右クリックで読むと、ハンドブックの「旧文明の記録」に次の記録が加わる。',
              'Right-click to read it and add the next ancient record to your handbook.'),
    'ストレンジ物質': ('ストレンジレットに変えられた超高密度の物質。質量値100の燃料で、縮退物質殻の材料にもなる。',
                'Ultra-dense matter left by strangelets. Worth 100 mass and usable for degenerate shells.'),
    'ストレンジレット': ('周りのブロックを毎秒1個ずつストレンジ物質に変えていく危険な物質。磁気瓶で封じ込めて回収する。',
                 'Converts nearby blocks into strange matter. Contain it with a Magnetic Bottle.'),
    '磁気単極子': ('粒子加速器の衝突でごく稀（約1/1000）に生まれる理論上の粒子。', 'A theoretical particle born in about 1 of 1000 collisions.'),
    # ---------------------------------------------------------------- 段階3 量子
    'ヘリウム': ('深層岩などを砕くと出る。冷却塔で液体ヘリウムにする。', 'Extracted from deep rock. Liquefy it in the tall tower.'),
    '液体ヘリウム': ('4 K の冷却材。量子部品とボース凝縮に要る。', 'A 4 K coolant for quantum parts.'),
    'データカード（量子データ片）': ('量子データ片を書き写したカード。', 'A copy of a quantum data fragment.'),
    '量子演算モジュール': ('段階3以降の上位装置の頭脳。', 'The brain of advanced machines.'),
    '量子もつれ合成器': ('2個1組の量子もつれ素子を作る。', 'Produces entangled elements in pairs.'),
    '量子もつれ素子': ('必ず2個1組で生まれる素子。検出器や遠隔連携の材料。', 'Always made in pairs. Used in detectors and links.'),
    'レーザー冷却器': ('原子をレーザーで冷やし、冷却原子・光格子基板・BE凝縮触媒を作る。', 'Laser-cools atoms into cold atoms, lattices and condensates.'),
    '冷却原子': ('絶対零度近くまで冷えた原子。', 'Atoms cooled close to absolute zero.'),
    '光格子基板': ('光で原子を並べた基板。量子部品の土台。', 'Atoms held in a lattice of light.'),
    'BE凝縮触媒': ('ティア3の触媒。ミュオン触媒より強く長持ち。', 'Tier 3 catalyst.'),
    '量子熱機関': ('触媒の量子効果で発電する。触媒のティアが高いほど出力が大きい。', 'A catalyst-driven generator.'),
    '重力波検出器': ('最終実験施設（重力異常点）のおおよその方角と距離帯を教える。', 'Points toward the nearest gravitational anomaly.'),
    'ニュートリノ・スキャナー': ('使うと周りの遺構の部品と鉱石の輪郭を、地形越しに10秒間浮かび上がらせる。電力を使う。',
                      'Reveals ruins and ores through terrain for 10 seconds.'),
    '慣性スタビライザー': ('半径16ブロックの中で爆発がブロックを壊さないようにする（防爆のみ）。', 'Stops explosions from breaking blocks within 16 blocks.'),
    '残響共鳴器': ('残響の欠片を型にして複製する。', 'Copies echo shards using a template shard.'),
    '慣性制御ガントレット': ('右クリック長押しで目の前の1体（HP40以下）を浮かせたり引き寄せたりする。スニーク＋右クリックでモード切替。',
                     'Hold right-click to levitate or pull one small mob. Sneak-use to switch modes.'),
    # ---------------------------------------------------------------- 段階4 時間
    '圧縮ブロックLv2': ('圧縮ブロックLv1 を9個（混成なら8個）固めたもの。縮退熱炉の燃料。', 'Nine Lv1 blocks (eight if mixed). Fuel for the Degenerate Furnace.'),
    '圧縮ブロックLv3': ('さらに高密度に固めたブロック。', 'An even denser block.'),
    '圧縮ブロックLv2（混成）': ('3種類以上の元ブロックから作った Lv1 なら、8個で Lv2 になる。', 'Lv1 made from 3+ kinds of blocks needs only 8 for Lv2.'),
    '縮退炉外殻': ('縮退物質の圧力に耐える外殻。段階4〜5のマルチブロックの壁。', 'The casing of tier 4–5 multiblocks.'),
    '縮退圧縮炉コントローラ': ('縮退圧縮炉の頭脳。縮退炉外殻の 3×3×3 の箱の一面に置く（中心は空気）。', 'Part of a hollow 3×3×3 casing box.'),
    '縮退圧縮炉': ('物質を縮退するまで押しつぶすマルチブロック。縮退物質殻や炉殻を作る。', 'Crushes matter into degenerate shells and reactor parts.'),
    '金属圧縮ブロックLv1': ('金属だけを固めた圧縮ブロック。', 'A compressed block made only of metals.'),
    '金属圧縮ブロックLv2': ('金属圧縮ブロックをさらに固めたもの。人工星核の材料。', 'Denser metal block, used for artificial star cores.'),
    '縮退物質殻': ('中性子星の物質でできた殻。特異点の種を包む。', 'A shell of neutron-star matter.'),
    '鏡面プレート': ('C空洞の上下の面にする鏡。', 'Mirror for the top and bottom of the C-Cavity.'),
    'C空洞コントローラ': ('C空洞の頭脳。5×5×5 の間の3段の側面に置く。', 'Goes on the side of the 5×5×5 cavity.'),
    'C空洞': ('向かい合う鏡の間に負のエネルギー状態を作るマルチブロック。エキゾチック物質とアクシオン凝縮体を作る。',
                  'Creates negative energy between mirrors to make exotic matter.'),
    'アクシオン凝縮体': ('真空中のアクシオンを集めた凝縮体。', 'Condensed axions gathered from the vacuum.'),
    'データカード（培養データ）': ('培養データを書き写したカード。', 'A copy of culture data.'),
    '時間結晶育成槽': ('時間結晶触媒を育てる。実際に動いた時間で育ち、電力不足だと純度（寿命）が下がる。',
                 'Grows time crystal catalysts. Underpowering lowers their purity.'),
    '時間結晶触媒': ('ティア4の触媒。上位装置の多くがこれで動く。', 'Tier 4 catalyst used by most advanced devices.'),
    'エキゾチック物質': ('負のエネルギー密度を持つ物質。重力系の装置とワームホールの燃料。', 'Matter with negative energy density. Fuels gravity tech.'),
    '縮退熱炉ピストン部': ('縮退熱炉の上下の面の十字の4か所に置くピストン。', 'Pistons for the cross positions of the furnace faces.'),
    '縮退熱炉コントローラ': ('縮退熱炉の頭脳。7×7×9 の四隅の柱のどれかに置く。', 'Goes in a corner pillar of the 7×7×9 furnace.'),
    '縮退熱炉': ('圧縮ブロックLv2 を押しつぶした熱で 20 MFE/t を出す大型発電機。時間結晶触媒を使う。', 'A large generator burning Lv2 blocks.'),
    'トポロジカル導線': ('段階4の大容量ケーブル。', 'Tier 4 high-capacity cable.'),
    'トロイダル磁気コイル': ('ドーナツ形の強い磁場を作るコイル。', 'Makes a strong toroidal field.'),
    'SMESモジュール': ('大容量の蓄電ブロック。', 'High-capacity energy storage.'),
    '自動探査機ステーション': ('発見済みの下位の遺構へ探査機を飛ばし、回収物を自動で持ち帰る。', 'Sends probes to discovered ruins to fetch loot.'),
    '磁気瓶': ('磁場でストレンジレットを捕まえる瓶。漏れ出したストレンジ物質に使うと封じ込めて回収できる。',
            'Captures strangelets and contains leaking strange matter.'),
    # ---------------------------------------------------------------- 段階5 特異点
    'ホライズン・バス': ('段階5の最大容量ケーブル（1 tick に約2.1 GFE）。リアクターの点火に要る。', 'The tier 5 cable, needed to ignite the reactor.'),
    '炉殻ブロック': ('Pリアクターの3本の円環を作る外殻。', 'Shell of the reactor\'s three rings.'),
    'ジャイロ駆動部': ('リアクターの3本の円環が交わる6点に置く。', 'Placed where the reactor rings cross.'),
    '抽出ポート': ('リアクターの電力・燃料の搬入出口。リングの炉殻の代わりに、どこにでも好きな数だけ置ける（ジャイロ駆動部の位置を除く）。', 'Power/fuel port for the reactor. Replaces any ring shell block (not the gyro drives).'),
    'ワームホール生成器入出力口': ('ワームホール生成器の外殻の代わりに、どこにでも置ける入出力口。電力を入れ、できたワームホールの口を取り出せる。', 'Replaces any casing block of the Wormhole Generator. Feeds power in and lets the mouths out.'),
    '重力場安定化ユニット': ('炉心制御装置の材料。', 'A component of the core controller.'),
    '炉心制御装置': ('Pリアクターの頭脳。炉心の真下（中心から5下）に置き、画面から点火する。',
                 'Placed 5 below the core centre. Ignite the reactor from its screen.'),
    'Pリアクター': ('ブラックホールの回転からエネルギーを取り出す最終の発電所（最大約 2.1 GFE/t）。', 'Draws energy from a spinning black hole.'),
    'Hコレクター': ('触媒モードのリアクターでH凝縮体を集める。', 'Collects H-Condensate in catalyst mode.'),
    'ジェット・コレクター': ('リアクターのジェットからジェット凝縮体を集める。', 'Collects jet condensate from the reactor.'),
    'エルゴスフィア・リング': ('高スピンの炉心からエキゾチック物質を取り出す。', 'Extracts exotic matter from a fast-spinning core.'),
    'ジェット凝縮体': ('相対論的ジェットの粒子。人工星核の材料。', 'Particles from the relativistic jet.'),
    '人工星核': ('ネザースターの代わりになる星の核。', 'A star core that replaces nether stars.'),
    'H凝縮体': ('ホーキング放射を集めた凝縮体。シンギュラリティ・コアの材料。', 'Condensed Hawking radiation.'),
    '特異点封入台': ('特異点の種やシンギュラリティ・コアを作る。', 'Encapsulates singularities.'),
    '特異点の種': ('リアクターに入れて点火すると炉心になる。', 'Becomes a black hole core when ignited.'),
    'シンギュラリティ・コア': ('最上位（ティア5）の触媒。シールドの完全版、アンカーへの埋め込みなどに使う。', 'The tier 5 catalyst.'),
    'ハロー捕集器': ('稼働中の炉心から16ブロック以内に置くと、暗黒物質（ダークマター）を集める。', 'Gathers dark matter near a running core.'),
    'ダークマター': ('重力以外ほとんど反応しない物質。普通の入れ物からは漏れる。炉心に直接入れると質量になる。',
               'Interacts only through gravity. Leaks from ordinary containers.'),
    '重力閉じ込めタンク': ('ダークマターを保管できる唯一のタンク。壊すと中身ごと運べる。電力が切れると漏れる。',
                   'The only tank that holds dark matter. Keeps its contents when broken.'),
    'シールド発生塔コア': ('イベントホライズン・シールド発生塔の頭脳。3×3×9 の塔の底の中央に置く。', 'Bottom centre of the 3×3×9 shield tower.'),
    'イベントホライズン・シールド発生塔': ('半径32の中を爆発・荒らし・敵の湧きから守る塔。', 'Protects a 32-block radius from explosions, griefing and hostile spawns.'),
    'ワールドライン・アンカー（上位）': ('上位のアンカー（最大半径4）。シンギュラリティ・コアを埋め込むと消費なしで半径5になる。',
                          'Advanced chunk loader. Embedding a Singularity Core makes it free and maximal.'),
    'メトリック・ドライブ': ('持ち物に入れておくと、低重力・無重力（飛行）・高重力を切り替えられる。', 'Switch between low gravity, flight and high gravity.'),
    'グラビトン・マニピュレーター': ('ガントレットの完全版。左クリック長押しで浮遊・牽引・斥力・圧壊。浮遊中は右クリックでためて離すと投げ飛ばす。G キーで円錐範囲。',
                     'The full gravity tool. Hold left-click to use; while levitating, charge with right-click and release to throw.'),
    'Tコア': ('Tシリンダーの頭脳。3×3×7 の底の中央に置く。', 'Bottom centre of the 3×3×7 T-Cylinder.'),
    'Tシリンダー': ('周りの時間を速め、半径8の装置・かまど・作物を×2にする（実在の物理では作れない装置）。', 'Speeds up time within 8 blocks.'),
    'ワームホール生成器コア': ('ワームホール生成器の頭脳。3×3×3 の底の中央に置く。', 'Bottom centre of the 3×3×3 wormhole generator.'),
    'ワームホール生成器': ('100 MFE/t を10秒受けて、一対のワームホールの口を作る。', 'Creates a pair of wormhole mouths from 100 MFE/t for 10 s.'),
    '不安定なワームホールの口': ('60秒以内に固定化装置へ入れないと崩壊する。', 'Collapses unless stabilized within 60 s.'),
    'ワームホールの口': ('置くと対の口とつながる。エキゾチック物質で維持する。', 'Links to its twin. Needs exotic matter upkeep.'),
    'ワームホール固定化装置': ('不安定な口をエキゾチック物質で固定化し、置ける口にする。', 'Stabilizes wormhole mouths.'),
    'ワームホール・ポート': ('口から8ブロック以内に置くと、向こう側の装置と電力・アイテム・液体を直結する。', 'Links machines through a wormhole.'),
    # ---------------------------------------------------------------- 遺構の回収物
    '観測ログ': ('地表観測拠点で拾う記録。アーカイブ端末でデータカードに書き写して使う。', 'A record from observation posts. Copy it onto data cards.'),
    '劣化した制御ユニット': ('地表観測拠点で拾う部品。アーカイブ端末で修復すると使える。', 'A degraded part. Restore it in the Archive Terminal.'),
    '制御ユニット': ('修復した旧文明の制御ユニット。使用回数がある。', 'A restored ancient control unit with limited uses.'),
    '量子データ片': ('研究棟で拾う記録。', 'A record from research buildings.'),
    '劣化した冷却原子トラップ': ('研究棟で拾う部品。レーザー冷却器で復元する。', 'Restore it in the Laser Cooler.'),
    '冷却原子トラップ': ('復元した冷却原子トラップ。', 'A restored cold atom trap.'),
    '劣化した時間結晶の種': ('封鎖培養施設で拾う種。復元すると時間結晶を育てられる。', 'Restore it to grow time crystals.'),
    '時間結晶の種': ('時間結晶触媒の種。', 'Seed for time crystal catalysts.'),
    '培養データ': ('封鎖培養施設で拾う記録。', 'A record from the culture facility.'),
    '劣化したアノマリー・サンプル': ('最終実験施設で拾うサンプル。', 'A sample from the final lab.'),
    'アノマリー・サンプル': ('復元した重力異常のサンプル。', 'A restored anomaly sample.'),
    '休眠した特異点の種': ('ホライズン・ウォーデンが守る種。特異点封入台で目覚めさせる。', 'Guarded by the Horizon Warden. Awaken it in the encapsulator.'),
    '遺構パネル': ('旧文明の建材。', 'Ancient building panel.'),
    'ひび割れた遺構パネル': ('ひびの入った旧文明の建材。', 'Cracked ancient panel.'),
    '苔むした遺構パネル': ('苔に覆われた旧文明の建材。', 'Mossy ancient panel.'),
    '割れた遺構ガラス': ('旧文明の窓。', 'Ancient window glass.'),
    '遺構の照明': ('今も光る旧文明の照明。', 'An ancient lamp that still glows.'),
    '遺構保管庫': ('遺構の回収物が入った保管庫。空になってから数日で中身が戻る。', 'Holds ruin loot. Refills some days after emptied.'),
    '警備機ドック': ('警備ドローンを出撃させるドック。', 'Launches security drones.'),
    '封印コンソール': ('最終実験施設の封印。触れるとホライズン・ウォーデンが起動する。', 'Touch it to wake the Horizon Warden.'),
    '失活したミュオン触媒': ('使い切ったミュオン触媒。触媒反応器で一部を回収できる。', 'A used-up catalyst. Partly recyclable.'),
    '失活したBE凝縮触媒': ('使い切ったBE凝縮触媒。下のティアの触媒として約25%回収できる。', 'Recycle it into lower-tier catalysts.'),
    '失活した時間結晶触媒': ('使い切った時間結晶触媒。下のティアの触媒として約25%回収できる。', 'Recycle it into lower-tier catalysts.'),
    '失活したシンギュラリティ・コア': ('使い切ったシンギュラリティ・コア。下のティアの触媒として約25%回収できる。', 'Recycle it into lower-tier catalysts.'),
}
